//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HirCasaDesarrollo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int ClienteId { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public int Edad { get; set; }
        public string MontoSolicitud { get; set; }
        public string Estatus { get; set; }
        public int Aprobacion { get; set; }
        public System.DateTime FechaAlta { get; set; }
    }
}
