//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HirCasaDesarrollo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int ClienteId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<decimal> MontoSolicitud { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> Aprobación { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
    }
}
